# Dockerfile-qa
FROM nginx:stable-alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Use our QA config (no SSL)
COPY nginx-qa.conf /etc/nginx/conf.d/

# Copy the built React app
COPY build/ /usr/share/nginx/html/

# Expose HTTP only
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
