# Dockerfile-qa
FROM nginx:stable-alpine

# Copy SSL certificate and key into the container
COPY cert-qa.crt /etc/ssl/certs/
COPY cert-qa.key /etc/ssl/private/

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Use our QA config (no SSL)
COPY nginx-qa.conf /etc/nginx/conf.d/

# Copy the built React app
COPY build/ /usr/share/nginx/html/

# Expose HTTP only
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
