export const tableHeaders = [
  'Part Number*',
  'Part Name*',
  'Part Description',
  'Parent Part Number*',
  'Req. QTY*',
  'Fnd. QTY',
  'Req. CND*',
  'Fnd. CND',
  'Suppl. LT',
  'Client LT',
  'Unit Price',
  'Supplier',
  'Total',
  'Comments',
  'DGPackagingCost',
  'Tag Date',
  'Last Updat. Date',
  'Cert. Type',
  'MSN',
  'Warehouse',
  'Stock',
  'Stock Loc.',
  'Airline Com.',
  'MSDS'
];
